(() => {
  const DATA = window.ACTIVITY_DATA || { title: 'Course Presentation', slides: [] };
  const $ = (id) => document.getElementById(id);
  const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const fallback = { type:'text', title:'Folie', text:'Kein Inhalt vorhanden.', answers:['Antwort 1'], correctIndex:0, pairs:[{item:'Begriff',target:'Ziel'}], dragText:'Text mit [Lücke].', interactions:[] };
  const slides = Array.isArray(DATA.slides) && DATA.slides.length ? DATA.slides : [fallback];
  let active = 0;
  function norm(x){ return {...fallback, ...(x||{}), answers:Array.isArray(x?.answers)&&x.answers.length?x.answers:fallback.answers, pairs:Array.isArray(x?.pairs)&&x.pairs.length?x.pairs:fallback.pairs, interactions:Array.isArray(x?.interactions)?x.interactions:[]}; }
  function renderMC(d){ d=norm(d); return `<article class="lite-content-block" data-lite-type="mc"><h2>${esc(d.question||d.title)}</h2><p>${esc(d.description||d.text||'')}</p><div class="h5p-lite-answer-stack">${d.answers.map((a,i)=>`<button class="iv-answer-button" type="button" data-correct="${i===Number(d.correctIndex)}">${esc(a)}</button>`).join('')}</div><div class="iv-feedback" hidden></div></article>`; }
  function renderDTW(d){ d=norm(d); const words=[]; const html=esc(d.dragText||d.text).replace(/\[([^\]]+)\]/g,(_,w)=>{words.push(w); return `<span class="dtw-blank" data-answer="${esc(w)}"></span>`}); return `<article class="lite-content-block" data-lite-type="dtw"><h2>${esc(d.title)}</h2><p>${html}</p><div class="dtw-word-bank">${words.map(w=>`<button class="dtw-chip" type="button" draggable="true">${esc(w)}</button>`).join('')}</div><button class="iv-primary-button lite-check-dtw" type="button">Prüfen</button><div class="iv-feedback" hidden></div></article>`; }
  function renderDND(d){ d=norm(d); const targets=[...new Set(d.pairs.map(p=>p.target))]; return `<article class="lite-content-block" data-lite-type="dnd"><h2>${esc(d.title)}</h2><p>${esc(d.description||'Ziehe die Begriffe in die passenden Felder.')}</p><div class="dnd-bank">${d.pairs.map(p=>`<button class="dnd-item" type="button" draggable="true" data-target="${esc(p.target)}">${esc(p.item)}</button>`).join('')}</div><div class="dnd-target-grid">${targets.map(t=>`<div class="dnd-target" data-target="${esc(t)}"><strong>${esc(t)}</strong></div>`).join('')}</div><button class="iv-primary-button lite-check-dnd" type="button">Prüfen</button><div class="iv-feedback" hidden></div></article>`; }
  function renderBlock(slide){ const d=norm(slide), media=String(d.media||'').trim(); if(d.type==='imageText') return `<article class="lite-content-block"><h2>${esc(d.title)}</h2>${media?`<img class="lite-media" src="${esc(media)}" alt="">`:''}<p>${esc(d.text)}</p></article>`; if(d.type==='video') return `<article class="lite-content-block"><h2>${esc(d.title)}</h2><p>${esc(d.text)}</p>${media?`<video class="lite-video" src="${esc(media)}" controls></video>`:'<p class="lite-note">Keine Video-URL eingetragen.</p>'}</article>`; if(d.type==='interactiveVideo') return `<article class="lite-content-block"><h2>${esc(d.title)}</h2><p>${esc(d.text)}</p>${media?`<div class="lite-iv-stage" data-interactions="${esc(JSON.stringify(d.interactions))}"><video class="lite-video" src="${esc(media)}" controls></video><div class="lite-glass-overlay" hidden></div></div>`:'<p class="lite-note">Keine Video-URL eingetragen.</p>'}</article>`; if(d.type==='multipleChoice') return renderMC(d); if(d.type==='dragWords') return renderDTW(d); if(d.type==='dragDrop') return renderDND(d); return `<article class="lite-content-block"><h2>${esc(d.title)}</h2><p>${esc(d.text)}</p></article>`; }
  function attach(root){ let dragged=null; root.querySelectorAll('[data-lite-type="mc"] .iv-answer-button').forEach(btn=>btn.onclick=()=>{const card=btn.closest('[data-lite-type="mc"]'); card.querySelectorAll('.iv-answer-button').forEach(b=>{b.disabled=true;if(b.dataset.correct==='true')b.classList.add('is-correct')}); if(btn.dataset.correct!=='true') btn.classList.add('is-wrong'); const f=card.querySelector('.iv-feedback'); if(f){f.hidden=false; f.textContent=btn.dataset.correct==='true'?'Richtig.':'Nicht ganz. Die richtige Antwort ist markiert.';}}); root.querySelectorAll('.dtw-chip,.dnd-item').forEach(ch=>{ch.ondragstart=()=>dragged=ch; ch.onclick=()=>dragged=ch;}); root.querySelectorAll('.dtw-blank').forEach(blank=>{const place=()=>{if(dragged?.classList.contains('dtw-chip')){blank.textContent=dragged.textContent; blank.dataset.filled=dragged.textContent; dragged.remove(); dragged=null;}}; blank.ondragover=e=>e.preventDefault(); blank.ondrop=place; blank.onclick=place;}); root.querySelectorAll('.dnd-target').forEach(zone=>{const place=()=>{if(dragged?.classList.contains('dnd-item')){zone.appendChild(dragged); dragged=null;}}; zone.ondragover=e=>e.preventDefault(); zone.ondrop=place; zone.onclick=place;}); root.querySelectorAll('.lite-check-dtw').forEach(btn=>btn.onclick=()=>{const card=btn.closest('[data-lite-type="dtw"]'), blanks=[...card.querySelectorAll('.dtw-blank')], f=card.querySelector('.iv-feedback'); const ok=blanks.length&&blanks.every(b=>b.dataset.filled===b.dataset.answer); blanks.forEach(b=>b.classList.toggle('is-correct',b.dataset.filled===b.dataset.answer)); if(f){f.hidden=false;f.textContent=ok?'Alles richtig.':'Noch nicht alles richtig.';}}); root.querySelectorAll('.lite-check-dnd').forEach(btn=>btn.onclick=()=>{const card=btn.closest('[data-lite-type="dnd"]'), items=[...card.querySelectorAll('.dnd-target .dnd-item')], all=card.querySelectorAll('.dnd-item').length, f=card.querySelector('.iv-feedback'); const ok=items.length===all&&items.every(i=>i.dataset.target===i.parentElement.dataset.target); items.forEach(i=>i.classList.toggle('is-correct',i.dataset.target===i.parentElement.dataset.target)); if(f){f.hidden=false;f.textContent=ok?'Alles richtig.':'Einige Zuordnungen stimmen noch nicht.';}}); }
  function render(){ active=Math.max(0,Math.min(active,slides.length-1)); const viewer=$('embeddedCpViewer'); if(!viewer) return; viewer.innerHTML = `<section class="viewer-card"><p class="eyebrow">${esc(DATA.title||'Course Presentation')}</p>${renderBlock(slides[active])}</section>`; const c=$('embeddedCpCount'); if(c)c.textContent=`Folie ${active+1} von ${slides.length}`; attach(viewer); }
  $('embeddedCpPrev')?.addEventListener('click', e=>{e.stopPropagation();active=Math.max(0,active-1);render();});
  $('embeddedCpNext')?.addEventListener('click', e=>{e.stopPropagation();active=Math.min(slides.length-1,active+1);render();});
  document.addEventListener('DOMContentLoaded', render);
  if(document.readyState !== 'loading') render();
})();
